name: Bug Report
description: Report a reproducible defect in behavior.
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide a minimal, reproducible case.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of the bug.
      placeholder: Incorrect fill accounting in portfolio after partial fills
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List exact steps and commands.
      placeholder: |
        1. Run `cargo test -p portfolio`
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What happened instead?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Output
      description: Paste relevant output from tests, clippy, or runtime logs.
      render: shell
  - type: input
    id: rust
    attributes:
      label: Rust Version
      description: Output of `rustc --version`.
      placeholder: rustc 1.xx.x (....)
  - type: input
    id: os
    attributes:
      label: OS / Environment
      description: OS and any notable environment details.
      placeholder: macOS 14, Ubuntu 24.04, etc.
